// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
#include "Components/RoofComponent.h"
#include "Components/GizmoComponent.h"
#include "Components/FootprintComponent.h"
#include "Actors/BuildTool.h"
#include "Actors/PlaceableObject.h"
#include "Interfaces/IDeletable.h"
#include "RoofBase.generated.h"

class ALotManager;
class UGizmoComponent;
class UWallPattern;

/**
 * Base Roof Actor for managing roof structures
 *
 * This actor-based approach provides:
 * - Better encapsulation of roof functionality
 * - Blueprint extensibility
 * - Self-contained scale tool management
 * - Independent wall generation/cleanup
 * - Cleaner separation from LotManager
 * - DEL key deletion support via IDeletable interface
 */
UCLASS(Abstract)
class BURBARCHITECT_API ARoofBase : public AActor, public IDeletable
{
	GENERATED_BODY()

public:
	// Sets default values for this actor's properties
	ARoofBase();

	// Called when an instance of this class is placed (in editor) or spawned
	virtual void OnConstruction(const FTransform& Transform) override;

protected:
	// Called when the game starts or when spawned
	virtual void BeginPlay() override;

	// Called when actor is being destroyed
	virtual void EndPlay(const EEndPlayReason::Type EndPlayReason) override;

public:
	// Called every frame
	virtual void Tick(float DeltaTime) override;

	// ==================== COMPONENTS ====================

	/** Root scene component */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Components")
	USceneComponent* RootSceneComponent;

	/** Roof mesh component - handles procedural mesh generation */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Components")
	URoofComponent* RoofMeshComponent;

	/** Footprint component for rendering roof footprint boundary lines */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Components")
	UFootprintComponent* FootprintComponent;

	/** Scale tool components for adjusting roof dimensions */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Scale Tools")
	UGizmoComponent* ScaleTool_Height;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Scale Tools")
	UGizmoComponent* ScaleTool_FrontExtent;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Scale Tools")
	UGizmoComponent* ScaleTool_BackExtent;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Scale Tools")
	UGizmoComponent* ScaleTool_LeftExtent;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Scale Tools")
	UGizmoComponent* ScaleTool_RightExtent;

	// ==================== PROPERTIES ====================

	/** Reference to the lot manager */
	UPROPERTY(Transient)
	ALotManager* LotManager;

	/** Current roof dimensions */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Roof Properties")
	FRoofDimensions RoofDimensions;

	/** Roof thickness */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Roof Properties")
	float RoofThickness;

	/** Gable thickness (for applicable roof types) */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Roof Properties")
	float GableThickness;

	/** Direction the roof faces */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Roof Properties")
	FVector RoofDirection;

	/** Current level the roof is on */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Roof Properties")
	int32 Level;

	/** Material for the roof */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Materials")
	UMaterialInstance* RoofMaterial;

	/** Default wall pattern for perimeter/gable walls generated by this roof */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Materials")
	UWallPattern* DefaultWallPattern;

	/** Whether the roof is in edit mode with scale tools visible */
	UPROPERTY(BlueprintReadOnly, Category = "State")
	bool bInEditMode;

	/** Whether the roof has been committed (finalized) */
	UPROPERTY(BlueprintReadOnly, Category = "State")
	bool bCommitted;

	/** Currently selected scale tool type */
	UPROPERTY(BlueprintReadOnly, Category = "Scale Tools")
	EScaleToolType CurrentScaleToolType;

	/** Drag operation vectors for scale tools */
	UPROPERTY(BlueprintReadOnly, Category = "Scale Tools")
	FToolDragOperation DragCreateVectors;

	/** Original roof dimensions at drag start (for snap-on-release) */
	FRoofDimensions OriginalDragDimensions;

	/** Last snapped dimensions for footprint preview */
	FRoofDimensions SnappedDimensions;

	/** Wall indices created by this roof for cleanup */
	UPROPERTY(Transient)
	TArray<int32> CreatedWallIndices;

	// ==================== METHODS ====================

	/** Initialize the roof with given parameters */
	UFUNCTION(BlueprintCallable, Category = "Roof")
	virtual void InitializeRoof(ALotManager* InLotManager, const FVector& Location, const FVector& Direction,
		const FRoofDimensions& InDimensions, float InRoofThickness = 15.0f, float InGableThickness = 20.0f);

	/** Generate the roof mesh - override in child classes */
	UFUNCTION(BlueprintCallable, Category = "Roof")
	virtual void GenerateRoofMesh();

	/** Update roof mesh when dimensions change */
	UFUNCTION(BlueprintCallable, Category = "Roof")
	virtual void UpdateRoofMesh();

	/** Commit the roof (finalize placement) */
	UFUNCTION(BlueprintCallable, Category = "Roof")
	virtual void CommitRoof();

	/** Enter edit mode and show scale tools */
	UFUNCTION(BlueprintCallable, Category = "Edit Mode")
	void EnterEditMode();

	/** Exit edit mode and hide scale tools */
	UFUNCTION(BlueprintCallable, Category = "Edit Mode")
	void ExitEditMode();

	/** Toggle edit mode */
	UFUNCTION(BlueprintCallable, Category = "Edit Mode")
	void ToggleEditMode();

	/** Rotate roof left (counter-clockwise) by 45 degrees */
	UFUNCTION(BlueprintCallable, Category = "Edit Mode")
	void RotateLeft();

	/** Rotate roof right (clockwise) by 45 degrees */
	UFUNCTION(BlueprintCallable, Category = "Edit Mode")
	void RotateRight();

	// ==================== SCALE TOOL METHODS ====================

	/** Setup scale tool positions based on current roof geometry */
	UFUNCTION(BlueprintCallable, Category = "Scale Tools")
	virtual void SetupScaleTools();

	/** Hide all scale tools */
	UFUNCTION(BlueprintCallable, Category = "Scale Tools")
	void HideScaleTools();

	/** Show all scale tools */
	UFUNCTION(BlueprintCallable, Category = "Scale Tools")
	void ShowScaleTools();

	/** Handle scale tool click */
	UFUNCTION()
	void OnScaleToolClicked(UGizmoComponent* TouchedComponent, FKey ButtonPressed);

	/** Handle confirm button click */
	UFUNCTION()
	void OnSubmitClicked(UGizmoComponent* TouchedComponent, FKey ButtonPressed);

	/** Process scale tool dragging */
	UFUNCTION(BlueprintCallable, Category = "Scale Tools")
	void ScaleToolDragged();

	/** Get scale tool component by type */
	UFUNCTION(BlueprintCallable, Category = "Scale Tools")
	UGizmoComponent* GetScaleToolByType(EScaleToolType Type);

	// ==================== WALL MANAGEMENT ====================

	/** Generate supporting walls for the roof */
	UFUNCTION(BlueprintCallable, Category = "Walls")
	virtual void GenerateSupportingWalls();

	/** Clean up all walls created by this roof */
	UFUNCTION(BlueprintCallable, Category = "Walls")
	void CleanupWalls();

	// ==================== FOOTPRINT VISUALIZATION ====================

	/** Draw footprint boundary lines showing the roof's grid area */
	void DrawFootprintLines(const FRoofDimensions* CustomDimensions = nullptr);

	/** Clear all footprint boundary lines */
	UFUNCTION(BlueprintCallable, Category = "Footprint")
	void ClearFootprintLines();

	// ==================== UTILITY ====================

	/** Get the roof type - override in child classes */
	UFUNCTION(BlueprintPure, Category = "Roof")
	virtual ERoofType GetRoofType() const { return ERoofType::Gable; }

	/** Check if a specific dimension is adjustable for this roof type */
	UFUNCTION(BlueprintPure, Category = "Scale Tools")
	virtual bool IsScaleToolValid(EScaleToolType ToolType) const;

	// ==================== IDELETABLE INTERFACE ====================

	/** Check if this roof can currently be deleted */
	virtual bool CanBeDeleted_Implementation() const override;

	/** Called before deletion to clean up walls and references */
	virtual void OnDeleted_Implementation() override;

	/** Check if this roof is currently selected/in edit mode */
	virtual bool IsSelected_Implementation() const override;

private:
	/** Setup a scale tool component with common properties */
	void SetupScaleToolComponent(UGizmoComponent* Component, EGizmoType Type);

	/** Update scale tool visibility based on edit mode */
	void UpdateScaleToolVisibility();

	/** Helper to get scale tool type from component */
	EScaleToolType GetScaleToolType(UGizmoComponent* Component);

	/** Check if we're currently in editor preview mode (not game world) */
	bool IsInEditorPreview() const;
};